require 'colorize'
require 'beezwax/core/abstractBeezwaxExecutor'
require 'beezwax/core/abstractBeezwaxManipulator'
require 'beezwax/core/abstractBeezwaxMonitor'
require 'beezwax/core/abstractBeezwaxSubject'
require 'beezwax/core/abstractBeezwaxProcessor'
require 'beezwax/core/beezwaxHoneypot'

require 'beezwax/bitflipManipulator'
require 'beezwax/clearSystemEventsProcessor'
require 'beezwax/crashlogDirectoryMonitor'
require 'beezwax/directoryCopierProcessor'
require 'beezwax/exitProcessor'
require 'beezwax/fileSubject'
require 'beezwax/mangleManipulator'
require 'beezwax/osxOpenProcessExecutor'
require 'beezwax/pdfManipulator'
require 'beezwax/processExecutor'
require 'beezwax/processKillProcessor'
require 'beezwax/processMonitor'
require 'beezwax/quicktimeCrashProcessor'
require 'beezwax/processor/CrashWranglerProcessor'

require 'beezwax/gdb/gdbWrapper'
